#!/usr/bin/env sh -e

USAGE="Usage: git branch-format <string> [prefix]"

if [ $# -eq 0 ]; then
    echo $USAGE
    exit 1
fi

INPUT="$1"

if [ "$2" != "" ]; then
    PREFIX="$2"
else
    PREFIX=""
fi

function branch_name_format() {
    local input="$1"
    local prefix="$2"

    local output=$(echo "$input" | sed -E 's|^[^:]+://||') # Remove the prefix *://
    output=$(echo "$output" | sed 's/[^a-zA-Z0-9]/ /g')    # Replace non-alphanumeric characters with spaces
    output=$(echo "$output" | awk '{$1=$1;print}')         # Strip leading and trailing whitespace
    output=$(echo "$output" | awk '{print tolower($0)}')   # Convert to lowercase
    output=$(echo "$output" | sed 's/ [ ]*/-/g')           # Replace spaces with hyphens
    output=$(echo "$prefix$output")

    echo "$output"
}

BRANCH_NAME=$(branch_name_format "$INPUT" "$PREFIX")

git branch "$BRANCH_NAME"

echo $BRANCH_NAME
