#!/bin/bash

# merge all remote tracking branches into local branches (Fast-Forward only)
# Supply -f,--fetch flag to also fetch all remote tracking branches before merge

if [[ "$1" == "-f" ]] || [[ "$1" == "--fetch" ]]; then
    git fetch --all
fi

# pull current checkout branch
git merge --ff-only "@{upstream}"

# pull all other branches
git for-each-ref --format='git fetch . %(upstream):%(refname)' refs/heads/ | sh
