#!/bin/bash

# check whether `git merge` from <branch_name> to current checkout branch is possible

if [ "$1" = "" ]; then
    echo "Usage: git check-merge <branch_name>"
    exit
else
    BRANCH_TO_MERGE=$1
fi

if ! git rev-parse --quiet --verify $BRANCH_TO_MERGE &>/dev/null; then
    echo "Branch '$BRANCH_TO_MERGE' does not exist"
    exit
fi

HEAD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "$BRANCH_TO_MERGE --> $HEAD_BRANCH"

if git merge --no-commit --no-ff $BRANCH_TO_MERGE &>/dev/null; then
    echo "Merge is possible"
else
    echo "Conflicts found"
fi

git merge --abort &>/dev/null
